apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
  namespace: job-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: nikhilmindfire/service-a:latest
          ports:
            - containerPort: 5001
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: job-system
spec:
  selector:
    app: service-a
  ports:
    - port: 5001
      targetPort: 5001
