apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  namespace: job-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
        - name: service-c
          image: nikhilmindfire/service_c:latest
          ports:
            - containerPort: 5003
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
  namespace: job-system
spec:
  selector:
    app: service-c
  ports:
    - port: 5003
      targetPort: 5003
